version: "3.5"
services:
    nginx:
        image: nginx:latest
        container_name: nginx
        networks:
          - main_network
        ports:
          - "8876:80"
        volumes:
          - './laravel:/var/www/laravel'
          - './_docker/nginx/conf.d:/etc/nginx/conf.d'
        restart: unless-stopped
    db:
        image: mysql:8
        container_name: db
        depends_on:
          - nginx
        networks:
          - main_network
        ports:
          - "8101:3306"
        volumes:
          - './mysql_db:/var/lib/mysql'
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: work
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    adminer:
        image: adminer
        container_name: adminer
        depends_on:
          - db
        networks:
          - main_network
        ports:
          - "8080:8080"
        restart: always
    application:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        container_name: application
        depends_on:
          - db
        networks:
          - main_network
        volumes:
          - './laravel:/var/www/laravel'
        restart: always

networks:
    main_network:
        driver: bridge